
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
# updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page


# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:Altman29/csy.github.io.git
  branch: main


# å·²æ¢æ˜


# Site
title: æ‹¾å | Space
#subtitle: 'ä»£ç åˆ°ç°å®1'
description: 'ä»Šå¤©ä¹Ÿè¦å¼€å¿ƒå•Š~ğŸ¥'
keywords: 'Code2Reality.cn,java,android,js,Devops,spring,ä¸­é—´ä»¶,åˆ†å¸ƒå¼,å®¹å™¨åŒ–'
author: æ‹¾å
language: zh-CN
timezone: Asia/Shanghai
theme: butterfly
# ç½‘ç«™å‰¯æ ‡é¢˜
# the subtitle on homepage (ä¸»é subtitle)
subtitle:
  enable: true
  # Typewriter Effect (æ‰“å­—æ•ˆæœ)
  effect: true
  # loop (å¾ªç’°æ‰“å­—)
  loop: true
  # source èª¿ç”¨ç¬¬ä¸‰æ–¹æœå‹™
  # source: false é—œé–‰èª¿ç”¨
  # source: 1  èª¿ç”¨ä¸€è¨€ç¶²çš„ä¸€å¥è©±ï¼ˆç°¡é«”ï¼‰ https://hitokoto.cn/
  # source: 2  èª¿ç”¨ä¸€å¥ç¶²ï¼ˆç°¡é«”ï¼‰ http://yijuzhan.com/
  # source: 3  èª¿ç”¨ä»Šæ—¥è©©è©ï¼ˆç°¡é«”ï¼‰ https://www.jinrishici.com/
  # subtitle æœƒå…ˆé¡¯ç¤º source , å†é¡¯ç¤º sub çš„å…§å®¹
  source: false
  # å¦‚æœé—œé–‰æ‰“å­—æ•ˆæœï¼Œsubtitle åªæœƒé¡¯ç¤º sub çš„ç¬¬ä¸€è¡Œæ–‡å­—
  sub:
    - "è¡Œæœ‰ä¸å¾—ï¼Œåæ±‚è¯¸å·±!ğŸ¥ğŸ¥ğŸ¥"
    - "åœ£äººä¹‹é“ï¼Œå¾æ€§è‡ªè¶³!ğŸ¥ğŸ¥ğŸ¥"
    - "çŸ¥æ˜¯è¡Œä¹‹å§‹ï¼Œè¡Œæ˜¯çŸ¥ä¹‹æˆ!ğŸ¥ğŸ¥ğŸ¥"
    - "æ­¤å¿ƒå…‰æ˜ï¼Œäº¦å¤ä½•è¨€ï¼ğŸ¥ğŸ¥ğŸ¥"


# ä¸»é¢˜æ”¯æŒä»£ç å¤åˆ¶åŠŸèƒ½
highlight_copy: true
#ä»£ç æ¡†ä¸å±•å¼€ï¼Œéœ€ç‚¹å‡» '>' æ‰“å¼€
highlight_shrink: false 
# é«˜äº®
highlight_theme: mac light

# å¯¼èˆªæ 
menu:
  é¦–é¡µ: / || fas fa-home
  æ—¶é—´è½´: /archives/ || fas fa-archive
  æ ‡ç­¾: /tags/ || fas fa-tags
  åˆ†ç±»: /categories/ || fas fa-folder-open
  # æ¸…å•||fa fa-heartbeat:
  #   éŸ³ä¹: /music/ || fas fa-music
  #   ç…§ç‰‡: /Gallery/ || fas fa-images
  #   ç”µå½±: /movies/ || fas fa-video
  #å‹é“¾: /link/ || fas fa-link
  å…³äº: /about/ || fas fa-heart

# A simple 404 page
error_404:
  enable: true
  subtitle: "é¡µé¢æ²’æœ‰æ‰¾åˆ°"
  background: /img/404.png

# ç¤¾äº¤å›¾æ ‡
social:
  fab fa-github: https://github.com/altman29 || Github
  fas fa-envelope: mailto:altman29@foxmail.com || Email


# é¦–é¡µå›¾ç‰‡èµ„æº
index_img: blue

# ç½‘ç«™èƒŒæ™¯
# å›¾ç‰‡æ ¼å¼ url(http://xxxxxx.com/xxx.jpg)
# é¢œè‰²ï¼ˆHEXå€¼/RGBå€¼/é¢œè‰²å•è¯/æ¸å˜è‰²)
# ç•™ç©º ä¸æ˜¾ç¤ºèƒŒæ™¯
background:


# æ–‡ç« coveré…ç½®
cover:
  # æ˜¯å¦æ˜¾ç¤ºæ–‡ç« å°é¢
  index_enable: true
  aside_enable: false
  archives_enable: true
  # å°é¢æ˜¾ç¤ºçš„ä½ç½®
  # ä¸‰ä¸ªå€¼å¯é…ç½® left , right , both
  position: both
  # å½“æ²¡æœ‰è®¾ç½®coveræ—¶ï¼Œé»˜è®¤çš„å°é¢æ˜¾ç¤º
  default_cover: 
    #- img/spring.jpg

# åè®®
# post_copyright: true
# enable: true
# decode: false
# author_href:
# license: CC BY-NC-SA 4.0
# license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# æ‰“èµ
reward:
  enable: false
  QR_code:
    - img: /img/wechat.png
      link:
      text: wechat
    - img: /img/alipay.png
      link:
      text: alipay

# æ–‡ç« ç›®å½•
toc:
  post: true # æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤º TOC
  page: false # æ™®é€šé¡µé¢æ˜¯å¦æ˜¾ç¤º TOC
  number: true   # æ˜¯å¦æ˜¾ç¤ºç« èŠ‚æ•°
  expand: false # æ˜¯å¦å±•å¼€ TOC
  style_simple: false # for post ç®€æ´æ¨¡å¼ï¼ˆä¾§è¾¹æ åªæ˜¾ç¤º TOC, åªå¯¹æ–‡ç« é¡µæœ‰æ•ˆ ï¼‰

# å¤´åƒ
avatar:
  img: /img/avatar.jpg
  effect: false # trueåˆ™ä¼šä¸€ç›´è½¬åœˆ


# copy settings
# copyright: Add the copyright information after copied content (å¤åˆ¶çš„å†…å®¹åé¢åŠ ä¸Šç‰ˆæƒä¿¡æ¯)
copy:
  enable: true  # æ˜¯å¦å¼€å¯ç½‘ç«™å¤åˆ¶æƒé™
  copyright:  # å¤åˆ¶çš„å†…å®¹åé¢åŠ ä¸Šç‰ˆæƒä¿¡æ¯
    enable: true  # æ˜¯å¦å¼€å¯å¤åˆ¶ç‰ˆæƒä¿¡æ¯æ·»åŠ 
    limit_count: 20 # å­—æ•°é™åˆ¶ï¼Œå½“å¤åˆ¶æ–‡å­—å¤§äºè¿™ä¸ªå­—æ•°é™åˆ¶æ—¶ï¼Œå°†åœ¨å¤åˆ¶çš„å†…å®¹åé¢åŠ ä¸Šç‰ˆæƒä¿¡æ¯

# footer
footer:
  owner:
    enable: true
    since: 2018 # ç«™ç‚¹èµ·å§‹æ—¶é—´
  #custom_text: çŸ¥è¡Œåˆä¸€ï¼Œç¬ƒè¡Œè‡´è¿œã€‚ # æ˜¯ä¸€ä¸ªç»™ä½ ç”¨æ¥åœ¨é¡µè„šè‡ªå®šä¹‰æ–‡æœ¬çš„é€‰é¡¹ã€‚é€šå¸¸ä½ å¯ä»¥åœ¨è¿™é‡Œå†™å£°æ˜æ–‡æœ¬ç­‰,æ”¯æŒ HTMLã€‚
  custom_text: çŸ¥è¡Œåˆä¸€ï¼Œç¬ƒè¡Œè‡´è¿œã€‚
  #<p><a target="_blank" href="https://hexo.io/"><img src="https://img.shields.io/badge/Frame-Hexo-blue?style=flat&logo=hexo" title="åšå®¢æ¡†æ¶ä¸ºHexo"></a>&nbsp;<a target="_blank" href="https://butterfly.js.org/"><img src="https://img.shields.io/badge/Theme-Butterfly-6513df?style=flat&logo=bitdefender" title="ä¸»é¢˜é‡‡ç”¨butterfly"></a>&nbsp;<a target="_blank" href="https://www.jsdelivr.com/"><img src="https://img.shields.io/badge/CDN-jsDelivr-orange?style=flat&logo=jsDelivr" title="æœ¬ç«™ä½¿ç”¨JsDelivrä¸ºé™æ€èµ„æºæä¾›CDNåŠ é€Ÿ"></a> &nbsp;<a target="_blank" href="https://vercel.com/ "><img src="https://img.shields.io/badge/Hosted-Vervel-brightgreen?style=flat&logo=Vercel" title="æœ¬ç«™é‡‡ç”¨åŒçº¿éƒ¨ç½²ï¼Œé»˜è®¤çº¿è·¯æ‰˜ç®¡äºVercel"></a>&nbsp;<a target="_blank" href="https://vercel.com/ "><img src="https://img.shields.io/badge/Hosted-Coding-0cedbe?style=flat&logo=Codio" title="æœ¬ç«™é‡‡ç”¨åŒçº¿éƒ¨ç½²ï¼Œè”é€šçº¿è·¯æ‰˜ç®¡äºCoding"></a>&nbsp;<a target="_blank" href="https://github.com/"><img src="https://img.shields.io/badge/Source-Github-d021d6?style=flat&logo=GitHub" title="æœ¬ç«™é¡¹ç›®ç”±Gtihubæ‰˜ç®¡"></a>&nbsp;<a target="_blank" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://img.shields.io/badge/Copyright-BY--NC--SA%204.0-d42328?style=flat&logo=Claris" title="æœ¬ç«™é‡‡ç”¨çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº«4.0å›½é™…è®¸å¯åè®®è¿›è¡Œè®¸å¯"></a></p>
  copyright: true # Copyright of theme and framework

# ç½‘ç«™ç»Ÿè®¡UVå’ŒPV
busuanzi:
  site_uv: true  # æœ¬ç«™æ€»è®¿å®¢æ•°
  site_pv: true  # æœ¬ç«™æ€»è®¿é—®é‡ 
  page_pv: true  # æœ¬æ–‡æ€»é˜…è¯»é‡


# Time difference between publish date and now (ç¶²é é‹è¡Œæ™‚é–“)
# Formal: Month/Day/Year Time or Year/Month/Day Time
runtimeshow:
  enable: true
  publish_date: 2/19/2018 13:43:09
  ##ç½‘é¡µå¼€é€šæ—¶é—´
  #æ ¼å¼: æœˆ/æ—¥/å¹´ æ—¶é—´
  #ä¹Ÿå¯ä»¥å†™æˆ å¹´/æœˆ/æ—¥ æ—¶é—´


# æœ€æ–°è¯„è®º
# Aside widget - Newest Comments
#newest_comments:
#  enable: true
#  sort_order: # Don't modify the setting unless you know how it works
#  limit: 6  # æ˜¾ç¤ºçš„æ•°é‡
#  storage: 10 # è®¾ç½®ç¼“å­˜æ—¶é—´ï¼Œå•ä½ åˆ†é’Ÿ 
#  avatar: true # æ˜¯å¦æ˜¾ç¤ºå¤´åƒ


# Typewriter Effect (æ‰“å­—æ•ˆæœ)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: true
  colorful: true # open particle animation (å†’å…‰ç‰¹æ•ˆ)
  shake: true #  open shake (æŠ–å‹•ç‰¹æ•ˆ)
  mobile: false


# å½©å¸¦åŠ¨æ•ˆ
canvas_fluttering_ribbon:
  enable: true
  mobile: true # false æ‰‹æœºç«¯ä¸æ˜¾ç¤º true æ‰‹æœºç«¯æ˜¾ç¤º

# é¼ æ ‡ç‚¹å‡»æ•ˆæœ
fireworks:
  enable: true
  zIndex: 9 # -1 or 9999
  mobile: false

# blogæ ‡é¢˜å­—ä½“
# Font settings for the site title and site subtitle
# https://fonts.googleapis.com/css?family=Titillium+Web&display=swap
# Titillium Web, 'PingFang SC' , 'Hiragino Sans GB' , 'Microsoft JhengHei' , 'Microsoft YaHei' , sans-serif
# å·¦ä¸Šè§’ç¶²ç«™åå­— ä¸»é å±…ä¸­ç¶²ç«™åå­—
blog_title_font: 'Hiragino Sans GB'
  #font_link:
  #font-family: var(--global-font)


# é¡µé¢åŠ è½½åŠ¨ç”»
# åŠ è½½åŠ¨ç”» Loading Animation
preloader: true


# å­—æ•°ç»Ÿè®¡
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true


# Pjax [Beta]
# It may contain bugs and unstable, give feedback when you find the bugs.
# https://github.com/MoOx/pjax
pjax: 
  enable: true
  # å¯¹äºä¸€äº›ç¬¬ä¸‰æ–¹æ’ä»¶ï¼Œæœ‰äº›å¹¶ä¸æ”¯æŒ pjax ã€‚
  # ä½ å¯ä»¥æŠŠç½‘é¡µåŠ å…¥åˆ° exclude é‡Œï¼Œè¿™ä¸ªç½‘é¡µä¼šè¢« pjax æ’é™¤åœ¨å¤–ã€‚
  # ç‚¹å‡»è¯¥ç½‘é¡µä¼šé‡æ–°åŠ è½½ç½‘ç«™ã€‚
  exclude: 
    - /music/
    - /no-pjax/


# inject
inject:
  head:
    - <link rel="stylesheet" href="/css/transpancy.css"> 
    #- <link rel="stylesheet" href="/css/progress_bar.css" media="defer" Î¿nlÎ¿ad="this.media='all'"> 
  bottom: 
    #- <script async src="//npm.elemecdn.com/pace-js@1.2.4/pace.min.js"></script>




# è¯„è®º
comments:
  use: Twikoo
  text: true # æ˜¯å¦æ˜¾ç¤ºè¯„è®ºæœåŠ¡å•†çš„åå­—
  lazyload: true
  count: true # æ˜¯å¦åœ¨æ–‡ç« é¡¶éƒ¨æ˜¾ç¤ºè¯„è®ºæ•°
  card_post_count: false # æ˜¯å¦åœ¨é¦–é¡µæ–‡ç« å¡ç‰‡æ˜¾ç¤ºè¯„è®ºæ•°

# Twikoo
twikoo:
  envId: https://hexo-blog-twikoo-flame.vercel.app/
  region:
  visitor: true
  option:


aside:
  card_author:
    enable: true
    description: ä»Šæ—¥äº‹ï¼Œä»Šæ—¥æ¯•ã€‚
    button:
      enable: false
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/xxxxxx

darkmode:
  enable: false